name: semantic-pull-request
on:
  pull_request:
    branches: 
      - develop
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Optionally you can configure which types are allowed.
        # Default: https://github.com/commitizen/conventional-commit-types
